### PR TITLE
Cache guava

### PR DESCRIPTION
**Pull request by kermitt2**
Better cache for concept relatedness, avoiding never ending growing...

### CODE REVIEW

**Comment by kermitt2** [comment]
@lfoppiano is there a dependency missing in the pom thingy regarding `com.sun.istack.internal.NotNull` ? Thanks!

```
[INFO] -------------------------------------------------------------
[ERROR] COMPILATION ERROR : 
[INFO] -------------------------------------------------------------
[ERROR] /home/lopez/entity-fishing/src/main/java/com/scienceminer/nerd/disambiguation/Relatedness.java:[13,31] package com.sun.istack.internal does not exist
[ERROR] /home/lopez/entity-fishing/src/main/java/com/scienceminer/nerd/disambiguation/Relatedness.java:[71,85] cannot find symbol
  symbol: class NotNull
[INFO] 2 errors 
```

**Comment by lfoppiano** [comment]
I need to try on my home computer. 
I think you can drop that out, unless there is a @NotNull in Guava. I think the import isn't right.

**Comment by lfoppiano** [comment]
Yes, just remove that @NotNull and let me know if its' working

**Comment by kermitt2** [comment]
It works fine thank you Luca !

**Pull request merged**
